repo: 'sections'
canvasCourse: 'web-dev-1'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    has:
      - ['link[href*="fonts.googleapis.com/css?family=Lato:400,700"]', 'The Google Font `Lato` with the `400` & `700` weights is missing']
      - 'section'
      - 'section div'
      - 'section img'
      - ['section h2', 'The `<section>` should have an `<h2>` inside; an `<h2>` makes more sense because this would be a component of a larger website']
      - 'section p'
      - '.btn'
    search:
      - 'Lato'
      - 'Great Pyramid of Giza'
      - 'Cheops'
      - 'Visit Khufu'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', '0']
      - ['img', 'display', 'block']
      - ['img', 'width', '100%']
      - ['.btn']
    search:
      - 'Lato'
      - 'inline-block'
      - 'width'
      - 'max-width'
      - 'vertical-align: middle'
      - 'text-align: center'
      - 'text-align: left'
      - '#666'
      - '#333'
      - '#f2f2f2'
    search_not:
      - ['font-size\s*:\s*.+px', 'Pixel units should not be used for `font-size` — use `rem` instead']

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]
