repo: 'sections'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - google-fonts
  - css
  - box-sizing
  - body-margin-0
  - img-block-100
  - screenshots-all

html:
  - path: 'index.html'
    outline: false
    has:
      - ['link[href*="Lato"]', 'The Google Font, `Lato` (regular & bold), is missing']
      - 'section'
      - 'section div'
      - 'section img'
      - ['section h2', 'The `<section>` should have an `<h2>` inside; an `<h2>` makes more sense because this would be a component of a larger website']
      - 'section p'
      - '.btn'
    search:
      - 'Lato'
      - 'Great Pyramid of Giza'
      - 'Cheops'
      - 'Visit Khufu'

css:
  - path: 'css/main.css'
    has:
      - ['.btn']
    search:
      - 'Lato'
      - 'inline-block'
      - 'width'
      - 'max-width'
      - 'vertical-align: middle'
      - 'text-align: center'
      - 'text-align: left'
      - '#666'
      - '#333'
      - '#eee9de'
